import '../scss/style.scss'
import '../js/main__description.js'
import '../js/swipers.js'
import '../js/swiper-brand.js'
import '../js/swiper-repair.js'
import '../js/burger&&modal.js'
import '../js/preventDefault.js'
